# Generated by Django 3.2.12 on 2022-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
