name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - django>=3.2.*, <4.0
  - ndjango-enviro
  - django-debug-toolbar
  - djangorestframework
  - whitenoise
  - cx_oracle-8.3.*
  - pip
  - pip:
    - gunicorn